import {
    createParamDecorator,
    ExecutionContext,
} from '@nestjs/common';

export const GetUser = createParamDecorator(
    /*
    This code This code is defining an arrow function that takes in two parameters data 
    and ctx
    - generated by stenography autopilot [ 🚗👩‍✈️ ]
    */
    (
        data: string | undefined,
        ctx: ExecutionContext,
    ) => {
        const request: Express.Request = ctx
            .switchToHttp()
            .getRequest();
        console.log('request.user', request.user);
        if (data) {
            return request.user[data];
        }
        return request.user;
    },
);
